-- Generated by Luapress v3.0

local config = {
    url = 'http://localhost:8000',

    -- Blog title
    title = 'Pointless Ramblings',

    -- Template name
    template = 'pointless_v10',

    -- Posts per page
    posts_per_page = 5,

    -- Date formatting
    date_format = '%a %d %B %Y',

    -- Environments!
    envs = {
        production = {
            url = 'http://pointlessramblings.com',
            build_dir = 'production'
        }
    }
}

return config
