-- Generated by Luapress v3.0

local config = {
    -- Blog base url (default)
    url = '/Pointless Ramblings/src/build',

    -- Blog title
    title = 'Pointless Ramblings',

    -- Template name
    template = 'pointless',

    -- Posts per page
    posts_per_page = 3,

    -- Date formatting
    date_format = '%a %d %B %Y',

    -- Environments!
    envs = {
        production = {
            url = 'http://pointlessramblings.com',
            build_dir = 'production'
        }
    }
}

return config
