-- Generated by Luapress v3.0

local config = {
    url = '',

    -- Blog title
    title = 'Pointless Ramblings',

    -- Template name
    template = 'pointless_v10',

    -- Posts per page
    posts_per_page = 3,

    -- Date formatting
    date_format = '%a %d %B %Y',

    -- Environments!
    envs = {
        production = {
            build_dir = 'production'
        }
    }
}

return config
